py_library(
    name = "scenario",
    srcs = [
        "scenario.py",
        "__init__.py"
    ],
    data = ['//bark:generate_core'],
    imports = ['../../../python'],
    deps = ["//bark/runtime/commons:parameters",
            "//bark/runtime/commons:commons",],
    visibility = ["//visibility:public"],
)